server:
  port: 8082

spring:
  profiles:
    active: default
  jackson:
    serialization:
      WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS: false

utils:
  dateformat: ddMMyyyy
  
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20