server:
  port: 8082

spring:
  profiles:
    active: default
  jackson:
    serialization:
      WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS: false

logging:
  level:
    org.springframework.retry: DEBUG---
utils:
  dateformat: ddMMyyyy