server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'

spring:
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SteveDZ/360-microservices-config.git

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20
#spring:
#  platform:
#    config:
#      server:
#        uri: https://github.com/SteveDZ/beers-microservice-config
#        basedir: config
#        basedir is the directory where the config reposistory will be cloned into. By default that's tmp