server:
  port: 8888

logging:
  level:
    com.netflix.discovery: 'OFF'

spring:
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SteveDZ/360-microservices-config.git

---
spring:
  profiles: dev