server:
  port: 7980

spring:
  profiles:
    active: local

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20