server:
  port: 9900

zuul:
  prefix: /api
  routes:
    persons:
      path: /persons/**
      serviceId: person-service
      stripPrefix: false
    timelines:
      path: /timeline/**
      serviceId: timeline-service
      stripPrefix: false

logging:
  level:
    com:
      netflix:
        discovery: 'DEBUG'

spring:
  profiles:
    active: local

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 20